blog/urls.py
# from django.urls import path,re_path
from django.urls import path
from .views import (
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    PostList2View,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", PostListView.as_view(), name="posts_list"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("new/", PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/edit/", PostUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("posts_list2/", PostList2View.as_view(), name="posts_list2"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    # path("catalog/", include("catalog.urls", namespace="catalog")),
    path("favicon.ico", RedirectView.as_view(url="/static/img/favicon.ico")),
    path("blog/", include("blog.urls", namespace="blog")),
    path('users/', include('users.urls', namespace="users")),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from unidecode import unidecode
from django.utils.text import slugify


def generate_unique_slug(klass, field):
    origin_slug = slugify(unidecode(field))
    unique_slug = origin_slug
    numb = 1
    while klass.objects.filter(slug=unique_slug).exists():
        unique_slug = f"{origin_slug}-{numb}"
        numb += 1
    return unique_slug


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(
        upload_to="photos/",
        null=True,
        blank=True,
        default="photos/default.jpg",
        verbose_name="Изображение",
    )
    created_at = models.DateTimeField(verbose_name="Дата публикации", auto_now_add=True)
    published = models.BooleanField(verbose_name="Статус публикации", default=True)
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")
    slug = models.SlugField(max_length=255, verbose_name="URL", null=False, unique=True)

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_unique_slug(Post, self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Post


class PostCreateView(CreateView):
    """создание поста"""

    model = Post
    fields = ["title", "body", "preview"]
    template_name = "blog/post_form.html"
    success_url = reverse_lazy("blog:posts_list")


class PostListView(ListView):
    """список постов"""

    model = Post

    template_name = "blog/posts_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        # queryset = super().get_queryset().filter(published=True)
        # return queryset.order_by("-id")
        return Post.objects.filter(published=True)


class PostDetailView(DetailView):
    """детальное описание поста"""

    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = "post"

    # def get_object(self):
    #     # Переопределение метода get_object
    #     obj = super().get_object()
    #     obj.views_count = obj.views_count + 1
    #     obj.save()
    #     return obj

    def get_object(self, queryset=None):
        # Переопределение метода get_object
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PostUpdateView(UpdateView):
    """обновление поста"""

    model = Post
    fields = ["title", "body", "published", "preview", "views_count"]
    template_name = "blog/post_form.html"

    # success_url = reverse_lazy('blog:posts_list')
    # def get_success_url(self):
    #     pk = self.kwargs["pk"]
    #     return reverse_lazy("blog:post_detail", kwargs={"pk": pk})
    def get_success_url(self):
        return reverse_lazy("blog:post_detail", args=[self.kwargs.get("pk")])


class PostDeleteView(DeleteView):
    """удаление поста"""

    model = Post
    template_name = "blog/post_confirm_delete.html"
    success_url = reverse_lazy("blog:posts_list")


class PostList2View(ListView):
    """список постов"""

    model = Post
    paginate_by = 3

    template_name = "blog/posts_list2.html"
    context_object_name = "posts"

    def get_queryset(self):
        # queryset = super().get_queryset().filter(published=True)
        # return queryset.order_by("-id")
        return Post.objects.filter(published=True)

blog/templates/blog/post_confirm_delete.html
<!-- mymodel_confirm_delete.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Удаление поста</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Удалить пост</h1>
        <p>Вы уверены, что хотите удалить "{{ post.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'blog:posts_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/post_detail.html
<!-- post_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Детали поста</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">{{ post.title }}</h1>
        <p>{{ post.body }}</p>
        <img src=/media/{{post.preview}} class="img-thumbnail">
        <p>Дата публикации : {{ post.created_at }}</p>
        <p>Пост опубликован : {{ post.published }}</p>
        <p>Количество просмотров : {{ post.views_count }}</p>


        <a href="{% url 'blog:post_edit' post.pk %}" class="btn btn-secondary">Редактировать</a>
        <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'blog:posts_list' %}" class="btn btn-primary">Вернуться к списку</a>



    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/post_form.html
<!-- post_form.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Создание поста</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Пост</h1>
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'blog:posts_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/posts_list.html
<!-- posts_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Посты</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Список постов</h1>
        <a href="{% url 'blog:post_create' %}" class="btn btn-primary mb-3">Создать новый пост</a>

        <ul class="list-group">
            {% for post in posts %}
                <li class="list-group-item">

                    <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a>

                </li>
            {% endfor %}
        </ul>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/posts_list2.html
<!-- posts_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Посты</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Список постов</h1>
        <a href="{% url 'blog:post_create' %}" class="btn btn-primary mb-3">Создать новый пост</a>

        <ul class="list-group">
            {% for post in object_list %}
            <div class="post">
                <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a>
            </div>
        </ul>

        {% endfor %}
    <div class="pagination mt-4">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>



    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>