blog/urls.py
# from django.urls import path,re_path
from django.urls import path
from .views import (
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    PostList2View,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", PostListView.as_view(), name="posts_list"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("new/", PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/edit/", PostUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("posts_list2/", PostList2View.as_view(), name="posts_list2"),
]

catalog/urls.py
from django.urls import include, path

# from catalog import views
from catalog.apps import CatalogConfig
from catalog import views
from catalog.views import (
    send,
    ProductDetailView,
    ProductsListView,
    ContactListView,
    CategoryesListView,
)
from catalog.views import (
    ProductCreateView,
    ProductUpdateView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)
from catalog.views import ProductModListView, ProductModDetailView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    # url PROD
    path("", ProductsListView.as_view(), name="product_list"),
    path("catalog/", ProductsListView.as_view(), name="products_list"),
    path("catalog/contact/", ContactListView.as_view(), name="contact"),
    path(
        "catalog/product_detail/<int:pk>/",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
    # # url for CRUD
    # path("catalog/product/all", ProductModListView.as_view(), name="product_mod_list"),
    # path(
    #     "catalog/category/create", CategoryCreateView.as_view(), name="category_create"
    # ),
    # path(
    #     "catalog/category/<int:pk>/", CategoryUpdateView.as_view(), name="category_mod"
    # ),
    # path("catalog/category/all", CategoryesListView.as_view(), name="categoryes_list"),
    # path(
    #     "catalog/category/<int:pk>/delete/",
    #     CategoryDeleteView.as_view(),
    #     name="category_delete",
    # ),
    path("catalog/product/", ProductCreateView.as_view(), name="product_create"),
    path("catalog/product/<int:pk>/", ProductUpdateView.as_view(), name="product_mod"),
    path(
        "catalog/product_mod_list/",
        ProductModListView.as_view(),
        name="product_mod_list",
    ),
    path(
        "catalog/product_mod_detail/<int:pk>/",
        ProductModDetailView.as_view(),
        name="product_mod_detail",
    ),
    path(
        "catalog/product/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="product_delete",
    ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    # path("catalog/", include("catalog.urls", namespace="catalog")),
    path("favicon.ico", RedirectView.as_view(url="/static/img/favicon.ico")),
    path("blog/", include("blog.urls", namespace="blog")),
    path('users/', include('users.urls', namespace="users")),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import CustomUser


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование продукта",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="photos/",
        blank=True,
        null=True,
        default="photos/default.jpg",
        verbose_name="Изображение (превью)",
        help_text="Загрузите фото продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        help_text="Введите категорию",
        related_name="categories",
    )
    price = models.IntegerField(
        blank=True, null=True, verbose_name="Цена", help_text="Укажите цену за покупку"
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания (записи в БД)",
        help_text="Укажите дату создания (записи в БД)",
    )
    updated_at = models.DateField(
        auto_now=True,
        verbose_name="Дата последнего изменения (записи в БД)",
        help_text="Укажите дату последнего изменения (записи в БД)",
    )
    allowed_publication = models.BooleanField(
        default=False,
        verbose_name="Разрешение для публикации",
        help_text="Этот продукт разрешен для публикации",

    )
    owners = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name="Владелец продукта",
        default=1,
        related_name="name",
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category"]
        permissions = [
            ("can_unpublish_product", "Сan unpublish product"),
        ]

    def __str__(self):
        return self.name


class Contact(models.Model):
    country = models.CharField(
        default="Российская Федерация",
        max_length=50,
        verbose_name="Страна",
        help_text="Введите наименование страны",
    )
    tax_reg_number = models.CharField(
        max_length=12,
        verbose_name="ИНН",
        help_text="Введите номер налогоплательщика",
        blank=True,
        null=True,
    )
    address = models.CharField(
        max_length=250,
        verbose_name="Адрес",
        help_text="Введите адрес",
    )
    phone = models.CharField(
        max_length=12,
        verbose_name="Основной телефон",
        help_text="Введите номер телефона",
    )

    class Meta:
        verbose_name = "Контакты"
        verbose_name_plural = "Контакты"

    def __str__(self):
        return self.address

catalog/forms.py
# forms.py
from django import forms
from .models import Product, Category
from django.conf import settings
from django.core.exceptions import ValidationError

wrong_word_list = settings.WRONG_WORDS_LIST


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = ""

        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название категории"}
        )
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание"}
        )


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ['owners']
        # photo = forms.ImageField(label="Изображение")

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = ""

        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название продукта"}
        )
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание"}
        )
        self.fields["category"].widget.attrs.update({"class": "form-control"})
        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите цену"}
        )

    def clean_price(self):
        price = self.cleaned_data.get("price")
        # not isinstance(price, int) and
        if price <= 0:
            raise ValidationError("цена должна быть положительным целым числом")
        return price

    def clean_photo(self):
        image = self.cleaned_data.get("photo")
        if not image and image.size > 5 * 1024 * 1024:  # 5 MB
            raise ValidationError("Картинка очень большая ( > 5MB )")
        if not image and image.name.endswith(".jpg", ".jpeg", ".png"):
            raise ValidationError("Файл не является изображением")
        return image

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        description = cleaned_data.get("description")

        if name and set(wrong_word_list) & set(name.lower().split()):
            self.add_error("name", "Название не может содержать запрещенные слова")
        elif description and set(wrong_word_list) & set(description.lower().split()):
            self.add_error("name", "Описание не может содержать запрещенные слова")

catalog/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from catalog.models import Contact, Product, Category
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

# from config.settings import RECIPIENTS_EMAIL, DEFAULT_FROM_EMAIL
from .forms import ProductForm, CategoryForm


# Create your views here.


def send(request):
    return render(request, "catalog/send.html")


class ContactListView(ListView):
    model = Contact
    template_name = "catalog/contact.html"
    context_object_name = "contact"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.last()  # вывод первого

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        name = self.request.POST.get("name")
        phone = self.request.POST.get("phone")
        message = self.request.POST.get("message")

        # send_mail(f'{name} от {phone}', message,
        #           DEFAULT_FROM_EMAIL, RECIPIENTS_EMAIL)

        return self.render_to_response(context)


class CategoryesListView(ListView):
    model = Category
    template_name = "catalog/categoryes_list.html"
    context_object_name = "categoryes"


class CategoryCreateView(LoginRequiredMixin, CreateView):
    """создание категории продуктов"""

    model = Category
    form_class = CategoryForm
    template_name = "catalog/category_form.html"
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy("catalog:categoryes_list")


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "catalog/category_form.html"
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy("catalog:categoryes_list")


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    """удаление категории"""

    model = Category
    template_name = "catalog/category_confirm_delete.html"
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy("catalog:categoryes_list")


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    login_url = reverse_lazy('users:login')
    template_name = "catalog/product_detail.html"
    context_object_name = "product"


class ProductsListView(ListView):
    model = Product
    template_name = "catalog/products_list.html"
    context_object_name = "products"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(allowed_publication=True)
        queryset = queryset.order_by("name")
        return queryset


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy("catalog:product_mod_list")

    def form_valid(self, form):
        if 'allowed_publication' in form.changed_data:  # Проверка, было ли поле 'field2' изменено
            if not self.request.user.has_perm('catalog.can_unpublish_product'):
                return HttpResponseForbidden("Вы не можете изменять поле публикация.")

        product = form.save()
        user = self.request.user
        product.owners = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy("catalog:product_mod_list")

    # def test_func(self):
    #     # Проверяем, обладает ли пользователь нужным разрешением
    #     return self.request.user.has_perm('app_name.change_yourmodel')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owners:
            self.object.save()
            return self.object
        raise PermissionDenied
        # return HttpResponseForbidden("Вы не можете изменять чужой продукт.")

    def form_valid(self, form):
        if 'allowed_publication' in form.changed_data:  # Проверка, было ли поле 'field2' изменено
            if not self.request.user.has_perm('catalog.can_unpublish_product'):
                return HttpResponseForbidden("Вы не можете изменять поле публикация.")

        return super().form_valid(form)


class ProductModListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/products_list2.html"
    login_url = reverse_lazy('users:login')
    context_object_name = "products"


class ProductModDetailView(LoginRequiredMixin, DetailView):
    """детальное описание поста"""

    model = Product
    template_name = "catalog/product_detail_mod.html"
    login_url = reverse_lazy('users:login')
    context_object_name = "product"


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """удаление продукта"""

    model = Product
    template_name = "catalog/product_confirm_delete.html"
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy("catalog:product_mod_list")

    def dispatch(self, request, *args, **kwargs):

        obj = Product.objects.get(pk=kwargs['pk'])
        if obj.owners != request.user:
            if not request.user.has_perm('catalog.delete_product'):
                return HttpResponseForbidden("У вас нет разрешения на удаление этого продукта")

        return super().dispatch(request, *args, **kwargs)

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Сайт WebStore{% endblock %}</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">


</head>
<body>
{% include 'catalog/includes/navigate.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">WebStore</h1>
    {% if user.is_authenticated %}
        <p>Добро пожаловать, {{ user.username }}!</p>
    {% else %}
        <p class="lead">WebStore - это отличный магазин</p>
    {% endif %}

</div>

<div class="container">
    {% block content %}{% endblock %}
    {% include 'catalog/includes/footer.html' %}
</div>


<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block title %}Удаление  категории{% endblock %}

{% block content %}


    <div class="container mt-5">
        <h1 class="mb-4">Удалить категорию</h1>
        <p>Вы уверены, что хотите удалить "{{ category.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'catalog:categoryes_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>


    <script src="/static/js/bootstrap.bundle.min.js"></script>

{% endblock %}

catalog/templates/catalog/category_form.html
<!-- category_form.html -->
{% extends 'catalog/base.html' %}

{% block title %}Добавить/Редактировать категорию{% endblock %}

{% block content %}

<h2>{{ view.title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'catalog:categoryes_list' %}" class="btn btn-secondary">Отмена</a>

</form>
{% endblock %}

catalog/templates/catalog/categoryes_list.html
{% extends 'catalog/base.html' %}

{% block title %}Каталог продуктов{% endblock %}

{% block content %}
<div class="row text-center">
    {% for category in categoryes %}
        <div class="col-4">

            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{category.name}} </h4>
                </div>
                <div class="card-body">

                    <p class="card-text">{{category.description}}</p>
                    <a href="{% url 'catalog:category_mod' category.pk %}" class="btn btn-secondary">Редактировать</a>
                    <a href="{% url 'catalog:category_delete' category.pk %}" class="btn btn-danger">Удалить</a>

                </div>

            </div>

        </div>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}

    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12 ">
            <div class="card mb-4 box-shadow ">
                <div class="card-body">
                    <table class="table table-striped">

                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{contact.country}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{contact.tax_reg_number}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{contact.address}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>{{contact.phone}}</td>
                        </tr>

                    </table>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Текст сообщения" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block title %}Удаление  продукта{% endblock %}

{% block content %}


    <div class="container mt-5">
        <h1 class="mb-4">Удалить продукт</h1>
        <p>Вы уверены, что хотите удалить "{{ product.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'catalog:product_mod_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>


    <script src="/static/js/bootstrap.bundle.min.js"></script>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block title %}Описание продукта{% endblock %}

{% block content %}

   <div class="row text-center">
        <div class="col-6 ">
            <div class="card mb-4 box-shadow start-50">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{product.name}} </h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{product.price}}</h1>
                    <p class="card-text">{{product.description}}</p>

                    <img src=/media/{{product.photo}} class="img-thumbnail">
                    <h6 class="font-weight-normal">Категория: {{product.category.name}} </h6>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
   </div>
{% endblock %}

catalog/templates/catalog/product_detail_mod.html
{% extends 'catalog/base.html' %}

{% block title %}Описание продукта{% endblock %}

{% block content %}

   <div class="row text-center">
        <div class="col-6 ">
            <div class="card mb-4 box-shadow start-50">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{product.name}} </h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{product.price}}</h1>
                    <p class="card-text">{{product.description}}</p>

                    <img src=/media/{{product.photo}} class="img-thumbnail" width="200" ">
                    <h6 class="font-weight-normal">Категория: {{product.category.name}} </h6>
                    {% if perms.catalog.can_unpublish_product or user == product.owners %}
                    <a href="{% url 'catalog:product_mod' product.pk %}" class="btn btn-secondary">Редактировать</a>
                    <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
                     {% endif %}
                    <a href="{% url 'catalog:product_mod_list' %}" class="btn btn-primary">Вернуться к списку</a>

                </div>
            </div>
        </div>
   </div>
{% endblock %}

catalog/templates/catalog/product_form.html
<!-- product_form.html -->
{% extends 'catalog/base.html' %}

{% block title %}Добавить/Редактировать категорию{% endblock %}

{% block content %}
{% if object%}
<h4>Редактирование продукта</h4>
{% else %}
<h4>Создание продукта</h4>
{% endif %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'catalog:product_mod_list' %}" class="btn btn-secondary">Отмена</a>

</form>
{% endblock %}

catalog/templates/catalog/products_list.html
{% extends 'catalog/base.html' %}

{% block title %}Каталог продуктов{% endblock %}

{% block content %}
<div class="row text-center">
    {% for product in products %}
        <div class="col-3">

            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{product.name}} </h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{product.price}}</h1>
                    <p class="card-text">{{product.description|truncatechars:100}}</p>

                    <img src=/media/{{product.photo}} class="img-thumbnail">
                    <h6 class="font-weight-normal">Категория: {{product.category}} </h6>

                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>

                </div>
            </div>

        </div>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/products_list2.html
{% extends 'catalog/base.html' %}

{% block title %}Добавить/Редактировать продукт{% endblock %}

{% block content %}

        <h4 class="mb-4">Список продуктов</h4>
        {% if perms.catalog.add_product %}

            <a href="{% url 'catalog:product_create' %}" class="btn btn-primary mb-3">Создать новый продукт</a>

        {% endif %}


        <ul class="list-group">
            {% for product in object_list %}
            <div class="post">
                <a href="{% url 'catalog:product_mod_detail' product.pk %}">{{ product.name }}</a>
            </div>


            {% endfor %}
        </ul>

{% endblock %}